# CI for Frontend Service

name: frontend

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup nodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Build
        run: cd Quiz-front && npm ci

      - name: Unit tests
        run: echo "run tests"
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run eslint
        run: echo "run eslint"
  docker:
    runs-on: ubuntu-latest

    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker
        uses: actions/setup-buildx-action@v1

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}
